import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const doc=page=>page.evaluate(()=>window.paperdom.getDocument());
const element=async(page,id='api_gateway')=>(await doc(page)).pages[0].elements.find(e=>e.id===id);
const tools=async(page,tab)=>{if(!await page.getByRole('region',{name:'Presentation tools'}).isVisible())await page.getByRole('button',{name:'Tools',exact:true}).click();await page.getByRole('region',{name:'Presentation tools'}).getByRole('button',{name:tab,exact:true}).click();};
const action=(page,name)=>page.getByRole('region',{name:'Presentation tools'}).getByRole('button',{name,exact:true}).click();
const close=page=>page.getByRole('button',{name:'Close tools',exact:true}).click();
const tx=(page,operations)=>page.evaluate(operations=>window.paperdom.transaction({operations}),operations);
test.beforeEach(async({page})=>{await page.goto('/');await expect.poll(()=>page.evaluate(()=>Boolean(window.paperdom))).toBe(true);});
test('presentation arrows, Home, End, blackout, Escape and editing shortcuts leave document unchanged',async({page})=>{
 const before=await doc(page);await page.getByRole('button',{name:'Present',exact:true}).click();await expect(page.getByRole('dialog',{name:'Presentation'})).toBeVisible();
 await page.keyboard.press('ArrowRight');await expect(page.locator('.present-controls')).toContainText('2 / 3');await page.keyboard.press('End');await expect(page.locator('.present-controls')).toContainText('3 / 3');await page.keyboard.press('Home');await expect(page.locator('.present-controls')).toContainText('1 / 3');await page.keyboard.press('b');await expect(page.locator('.present-frame')).toBeHidden();await page.keyboard.press('b');await expect(page.locator('.present-frame')).toBeVisible();
 for(const key of ['Delete','Control+d','Control+z','t'])await page.keyboard.press(key);expect(await doc(page)).toEqual(before);await page.keyboard.press('Escape');await expect(page.locator('.present-overlay')).not.toBeVisible();expect(await doc(page)).toEqual(before);
});
test('notes, transitions, timing and hidden slides persist and present',async({page})=>{
 await tools(page,'Slides');await page.getByLabel('Speaker notes editor').fill('Explain each boundary.');await page.getByLabel('Slide transition').selectOption('fade');await page.getByLabel('Advance after seconds').fill('1');
 await page.getByLabel('Current slide').selectOption('page_annotation');await page.getByLabel('Skip this slide in presentation').check();await page.getByLabel('Current slide').selectOption('page_architecture');await close(page);
 const before=await doc(page);await page.getByRole('button',{name:'Present',exact:true}).click();await page.getByRole('button',{name:'Speaker notes',exact:true}).click();await expect(page.locator('.present-notes')).toContainText('Explain each boundary.');await expect(page.locator('.present-controls')).toContainText('2 / 2',{timeout:5000});expect(await doc(page)).toEqual(before);
});
for(const [size,w,h] of [['960x720',960,720],['720x1280',720,1280],['720x720',720,720]])test(`slide size ${size} scales canvas, objects and presentation`,async({page})=>{
 const before=await element(page);await tools(page,'Slides');await page.getByLabel('Slide size').selectOption(size);await close(page);await expect(page.locator('.page-canvas')).toHaveCSS('width',`${w}px`);await expect(page.locator('.page-canvas')).toHaveCSS('height',`${h}px`);expect((await element(page)).frame.x).toBeCloseTo(before.frame.x*w/1280);await page.getByRole('button',{name:'Present',exact:true}).click();await expect(page.locator('.present-frame .static-page')).toHaveCSS('width',`${w}px`);
});
test('table data editing and header toggle survive undo and reload',async({page})=>{
 await tools(page,'Objects');await action(page,'Insert table');await close(page);await page.getByLabel('Object data').fill('Name\tScore\nAda\t42');await page.getByLabel('Object data').press('Tab');await expect(page.locator('.page-canvas table')).toContainText('Ada');await page.getByLabel('Header row').uncheck();expect((await doc(page)).pages[0].elements.at(-1).table.header).toBe(false);await page.getByTitle('Undo',{exact:true}).click();expect((await doc(page)).pages[0].elements.at(-1).table.header).toBe(true);await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('paperdom:doc_paperdom_demo'))?.pages[0].elements.at(-1).table?.rows[1][0])).toBe('Ada');await page.reload();await expect(page.locator('.page-canvas table')).toContainText('Ada');
});
test('chart edits accept negative values and reject malformed data atomically',async({page},testInfo)=>{
 await tools(page,'Objects');await action(page,'Insert chart');await close(page);await page.getByLabel('Chart title').fill('Net growth');await page.getByLabel('Chart type').selectOption('line');await page.getByLabel('Object data').fill('January\t-2\nFebruary\t8');await page.getByLabel('Object data').press('Tab');const before=await doc(page);expect(before.pages[0].elements.at(-1).chart.values).toEqual([-2,8]);await page.getByLabel('Object data').fill('January\tNaN');await page.getByLabel('Object data').press('Tab');await expect(page.getByRole('alert')).toContainText('finite number');expect(await doc(page)).toEqual(before);await expect(page.locator('.page-canvas .slide-chart')).toHaveAttribute('aria-label',/Net growth/);const present=await page.getByRole('button',{name:'Present',exact:true}).boundingBox();expect(present.x+present.width).toBeLessThanOrEqual(1440);await page.screenshot({path:testInfo.outputPath('desktop-chart.png')});
});
test('copy, paste, cut, duplicate and undo preserve stable independent objects',async({page})=>{
 const before=await doc(page);await tools(page,'Objects');await action(page,'Copy');await action(page,'Paste');let after=await doc(page);expect(after.pages[0].elements.length).toBe(before.pages[0].elements.length+1);expect(after.pages[0].elements.at(-1).id).not.toBe('api_gateway');await action(page,'Cut');expect((await doc(page)).pages[0].elements.length).toBe(before.pages[0].elements.length);await action(page,'Paste');await action(page,'Duplicate');expect((await doc(page)).pages[0].elements.length).toBe(before.pages[0].elements.length+2);await close(page);await page.getByTitle('Undo',{exact:true}).click();expect((await doc(page)).pages[0].elements.length).toBe(before.pages[0].elements.length+1);
});
test('grouping and ungrouping are atomic and group selection follows click',async({page})=>{
 await page.locator('[data-element-id="web_app"]').click({modifiers:['Shift']});await tools(page,'Objects');await action(page,'Group');let d=await doc(page);const grouped=d.pages[0].elements.filter(e=>e.groupId);expect(grouped).toHaveLength(2);expect(grouped[0].groupId).toBe(grouped[1].groupId);await close(page);await page.keyboard.press('Escape');await page.locator('[data-element-id="web_app"]').click();await expect(page.locator('.inspector-heading')).toContainText('2 objects');await tools(page,'Objects');await action(page,'Ungroup');expect((await doc(page)).pages[0].elements.filter(e=>e.groupId)).toHaveLength(0);
});
test('layer lock blocks keyboard, inspector and direct text editing; hide and show work',async({page})=>{
 await tools(page,'Objects');await action(page,'Lock API gateway');await close(page);const before=await element(page);await expect(page.getByLabel('W',{exact:true})).toBeDisabled();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await page.keyboard.press('Delete');expect(await element(page)).toEqual(before);await tools(page,'Objects');await action(page,'Hide API gateway');await expect(page.locator('[data-element-id="api_gateway"]')).toHaveCount(0);await action(page,'Show API gateway');await action(page,'Unlock API gateway');await action(page,'Select API gateway');await close(page);await expect(page.getByLabel('W',{exact:true})).toBeEnabled();
});
test('aspect lock and numeric controls preserve valid dimensions',async({page})=>{const before=await element(page);await page.getByRole('button',{name:'Lock aspect ratio'}).click();await page.getByLabel('W',{exact:true}).fill('490');expect((await element(page)).frame.h).toBeCloseTo(before.frame.h*2);await page.getByLabel('W',{exact:true}).fill('-5');expect((await element(page)).frame.w).toBe(1);await page.getByLabel('%',{exact:true}).fill('200');expect((await element(page)).style.opacity).toBe(1);});
test('find, navigate and replace skip locked objects and support tables',async({page})=>{
 await tools(page,'Find');await page.getByLabel('Find text',{exact:true}).fill('API gateway');await expect(page.locator('.tools-results')).toContainText('API gateway');await page.getByLabel('Replace with').fill('Public API');await action(page,'Replace all');expect((await element(page)).content.text).toBe('Public API');await tx(page,[{op:'patchElement',elementId:'api_gateway',patch:{locked:true}}]);await page.getByLabel('Find text',{exact:true}).fill('Public API');await page.getByLabel('Replace with').fill('Blocked');await action(page,'Replace all');expect((await element(page)).content.text).toBe('Public API');
});
test('image replace preserves ID and geometry; oversized upload does not insert',async({page})=>{
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9l8AAAAASUVORK5CYII=','base64');const input=page.locator('input[type=file][accept^="image"]');await input.setInputFiles({name:'one.png',mimeType:'image/png',buffer:png});await expect.poll(async()=>(await doc(page)).pages[0].elements.at(-1).type).toBe('image');const before=await doc(page),image=before.pages[0].elements.at(-1);const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Replace image'}).click();await(await chooser).setFiles({name:'two.png',mimeType:'image/png',buffer:png});await expect.poll(async()=>(await doc(page)).revision).toBeGreaterThan(before.revision);const after=await doc(page);expect(after.pages[0].elements.length).toBe(before.pages[0].elements.length);expect(after.pages[0].elements.at(-1).id).toBe(image.id);expect(after.pages[0].elements.at(-1).frame).toEqual(image.frame);await input.setInputFiles({name:'large.png',mimeType:'image/png',buffer:Buffer.alloc(3*1024*1024)});expect((await doc(page)).pages[0].elements.length).toBe(after.pages[0].elements.length);
});
test('PowerPoint, HTML and JSON downloads have real content; print hides editor',async({page})=>{
 await tools(page,'Check & export');for(const [name,extension] of [['Download PowerPoint (.pptx)','.pptx'],['Download standalone HTML','.html'],['Download document JSON','.json']]){const wait=page.waitForEvent('download');await action(page,name);const download=await wait;expect(download.suggestedFilename()).toMatch(new RegExp(extension.replace('.','\\.')+'$'));const bytes=await readFile(await download.path());expect(bytes.length).toBeGreaterThan(100);if(extension==='.pptx')expect(bytes.subarray(0,2).toString()).toBe('PK');if(extension==='.html')expect(bytes.toString()).toContain('<!doctype html>');if(extension==='.json')expect(JSON.parse(bytes.toString()).format).toBe('paperdom');}await page.emulateMedia({media:'print'});await expect(page.locator('.print-deck')).toBeVisible();await expect(page.locator('.topbar')).not.toBeVisible();await expect(page.locator('.print-slide')).toHaveCount(3);
});
test('JSON malformed input does not mutate and Escape closes while typing',async({page})=>{const before=await doc(page);await page.getByRole('button',{name:'JSON',exact:true}).click();await page.getByRole('textbox',{name:'Document JSON',exact:true}).fill('{broken');await page.getByRole('button',{name:'Apply JSON'}).click();await expect(page.locator('.json-error')).toBeVisible();expect(await doc(page)).toEqual(before);await page.getByRole('textbox',{name:'Document JSON',exact:true}).press('Escape');await expect(page.locator('.json-panel')).not.toBeVisible();});
test('mobile tools expose slides, object properties, library and exports without horizontal document overflow',async({page},testInfo)=>{
 await page.setViewportSize({width:390,height:844});await tools(page,'Slides');await expect(page.getByLabel('Current slide')).toBeVisible();await page.getByLabel('Current slide').selectOption('page_architecture');await tools(page,'Objects');await action(page,'Select API gateway');await action(page,'Edit object properties');await expect(page.getByLabel('W',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Close inspector'}).click();await tools(page,'Check & export');await expect(page.getByRole('button',{name:'Download PowerPoint (.pptx)'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.screenshot({path:testInfo.outputPath('mobile-tools.png')});
});
for(const [name,type]of [['Rectangle','shape'],['Ellipse','ellipse'],['KPI plugin','plugin']])test(`toolbar inserts ${name} inside slide bounds`,async({page})=>{const before=await doc(page);await page.getByRole('button',{name,exact:true}).click();await page.locator('.page-canvas').click({position:{x:4,y:4},force:true});const e=(await doc(page)).pages[0].elements.at(-1);expect(e.type).toBe(type);expect(e.frame.x).toBeGreaterThanOrEqual(0);expect(e.frame.y).toBeGreaterThanOrEqual(0);expect((await doc(page)).pages[0].elements.length).toBe(before.pages[0].elements.length+1);});
test('text box creation, multiline editing and character/paragraph formatting commit',async({page})=>{
 await page.getByRole('button',{name:'Text box',exact:true}).click();await page.locator('.page-canvas').click({position:{x:20,y:20},force:true});const editor=page.getByRole('textbox',{name:'Edit Text box',exact:true});await expect(editor).toBeVisible();await editor.fill('Alpha\nBeta');await editor.press('Control+Enter');const id=(await doc(page)).pages[0].elements.at(-1).id;
 for(const name of ['Bold','Italic','Underline','Strikethrough','Bulleted list','Align right','bottom'])await page.getByRole('button',{name,exact:true}).click();await page.getByLabel('Font family',{exact:true}).selectOption({label:'Georgia'});await page.getByLabel('Size',{exact:true}).fill('30');const e=await element(page,id);expect(e.content.text).toContain('Alpha');expect(e.content.text).toContain('Beta');expect(e.style).toMatchObject({fontWeight:700,fontStyle:'italic',underline:true,strike:true,textAlign:'right',verticalAlign:'bottom',fontSize:30});
});
test('drag, resize, rotate and Escape rollback are reflected in document geometry',async({page})=>{
 const node=page.locator('[data-element-id="api_gateway"]'),before=await element(page),box=await node.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.keyboard.down('Alt');await page.mouse.move(box.x+box.width/2+30,box.y+box.height/2+20,{steps:5});await page.mouse.up();await page.keyboard.up('Alt');expect((await element(page)).frame.x).toBeGreaterThan(before.frame.x);
 const handle=await page.getByRole('button',{name:'Resize se',exact:true}).boundingBox();await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await page.mouse.down();await page.mouse.move(handle.x+40,handle.y+30,{steps:4});await page.mouse.up();expect((await element(page)).frame.w).toBeGreaterThan(before.frame.w);await page.getByLabel('°',{exact:true}).fill('30');expect((await element(page)).frame.rotation).toBe(30);
 const stable=await doc(page),b=await node.boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+60,b.y+b.height/2+30,{steps:4});await page.keyboard.press('Escape');await page.mouse.up();expect(await doc(page)).toEqual(stable);
});
for(const [tool,type]of [['Line','line'],['Arrow','connector']])test(`${tool} drawing, keyboard movement and duplication translate free endpoints`,async({page})=>{
 await page.getByRole('button',{name:tool,exact:true}).click();const b=await page.locator('.page-canvas').boundingBox();await page.mouse.move(b.x+20,b.y+20);await page.mouse.down();await page.mouse.move(b.x+100,b.y+25,{steps:4});await page.mouse.up();const line=(await doc(page)).pages[0].elements.at(-1);expect(line.type).toBe(type);expect(line.from.elementId).toBeUndefined();await page.keyboard.press('ArrowRight');const moved=await element(page,line.id);expect(moved.from.x).toBeCloseTo(line.from.x+1);await page.keyboard.press('Control+d');const copy=(await doc(page)).pages[0].elements.at(-1);expect(copy.from.x).toBeCloseTo(moved.from.x+20);expect(copy.to.x).toBeCloseTo(moved.to.x+20);
});
test('zoom and guide controls change view without changing document',async({page})=>{const before=await doc(page),width=(await page.locator('.page-canvas').boundingBox()).width;await page.getByRole('button',{name:'Zoom in',exact:true}).click();expect((await page.locator('.page-canvas').boundingBox()).width).toBeGreaterThan(width);await page.getByRole('button',{name:'Zoom out',exact:true}).click();await page.getByRole('button',{name:'Guides',exact:true}).click();await expect(page.getByRole('button',{name:'Guides',exact:true})).toHaveAttribute('aria-pressed','false');expect(await doc(page)).toEqual(before);});
test('front/back, fill, border, radius and opacity update selected object',async({page})=>{await page.getByRole('button',{name:'Front',exact:true}).click();let d=await doc(page);expect((await element(page)).z).toBe(Math.max(...d.pages[0].elements.map(e=>e.z)));await page.getByRole('button',{name:'Back',exact:true}).click();d=await doc(page);expect((await element(page)).z).toBe(Math.min(...d.pages[0].elements.map(e=>e.z)));await page.locator('.color-field').filter({hasText:'Fill'}).locator('input').fill('#123456');await page.locator('.color-field').filter({hasText:'Border'}).locator('input').fill('#abcdef');await page.getByLabel('R',{exact:true}).fill('8');await page.getByLabel('%',{exact:true}).fill('50');expect((await element(page)).style).toMatchObject({fill:'#123456',stroke:'#abcdef',radius:8,opacity:.5});});
test('alignment and both distribution directions arrange multiple objects atomically',async({page})=>{await page.locator('[data-element-id="web_app"]').click({modifiers:['Shift']});await page.locator('[data-element-id="database"]').click({modifiers:['Shift']});await tools(page,'Objects');await action(page,'Align top');let d=await doc(page);let items=d.pages[0].elements.filter(e=>['api_gateway','web_app','database'].includes(e.id));expect(new Set(items.map(e=>e.frame.y)).size).toBe(1);await action(page,'Distribute horizontal');d=await doc(page);items=d.pages[0].elements.filter(e=>['api_gateway','web_app','database'].includes(e.id)).sort((a,b)=>a.frame.x-b.frame.x);expect(items[1].frame.x-items[0].frame.x-items[0].frame.w).toBeCloseTo(items[2].frame.x-items[1].frame.x-items[1].frame.w);await action(page,'Distribute vertical');expect((await doc(page)).revision).toBeGreaterThan(d.revision);});
test('KPI properties edit independently and show in presentation',async({page})=>{await page.getByRole('button',{name:'KPI plugin',exact:true}).click();await page.locator('.page-canvas').click({position:{x:20,y:20},force:true});const panel=page.locator('.plugin-properties');await panel.getByLabel('Label',{exact:true}).fill('Revenue');await panel.getByLabel('Value',{exact:true}).fill('$42K');await panel.getByLabel('Trend',{exact:true}).fill('+8%');expect((await doc(page)).pages[0].elements.at(-1).content).toMatchObject({label:'Revenue',value:'$42K',trend:'+8%'});await page.getByRole('button',{name:'Present',exact:true}).click();await expect(page.locator('.present-frame')).toContainText('$42K');});
test('image drop and clipboard paste insert actual embedded image data',async({page})=>{const before=(await doc(page)).pages[0].elements.length;for(const type of ['drop','paste'])await page.evaluate(type=>{const data=new DataTransfer();data.items.add(new File([Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9l8AAAAASUVORK5CYII='),c=>c.charCodeAt(0))],'pixel.png',{type:'image/png'}));if(type==='drop')document.querySelector('.page-canvas').dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:data}));else window.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));},type);await expect.poll(async()=>(await doc(page)).pages[0].elements.length).toBe(before+2);expect((await doc(page)).pages[0].elements.slice(-2).every(e=>e.content.src.startsWith('data:image/png;base64,'))).toBe(true);});
test('exported HTML opens offline and navigation changes slides',async({page,context})=>{await tools(page,'Check & export');const wait=page.waitForEvent('download');await action(page,'Download standalone HTML');const download=await wait;const html=await readFile(await download.path(),'utf8');const offline=await context.newPage();await offline.route('**/*',route=>route.abort());await offline.setContent(html);await expect(offline.locator('#count')).toHaveText('1 / 3');await offline.getByRole('button',{name:'Next',exact:true}).click();await expect(offline.locator('#count')).toHaveText('2 / 3');await offline.keyboard.press('ArrowRight');await expect(offline.locator('#count')).toHaveText('3 / 3');await expect(offline.getByRole('button',{name:'Next',exact:true})).toBeDisabled();await offline.getByRole('button',{name:'Previous',exact:true}).click();await expect(offline.locator('#count')).toHaveText('2 / 3');});
