import {test} from 'node:test';
import assert from 'node:assert/strict';
import {collaborationHarness as harness} from './helpers/collaboration.mjs';
import {documentFixture} from './fixtures/document.mjs';

test('shared documents require authentication and reject cross-origin writes',async()=>{const {call}=harness();assert.equal((await call('','GET',null,null)).status,401);assert.equal((await call('','POST',{document:documentFixture()},'owner',{origin:'https://attacker.example'})).status,403);});
test('create, list, read, revision save and unchanged-version polling',async()=>{const{call}=harness(),d=documentFixture(),saved=await call('','POST',{document:d});assert.equal(saved.status,201);assert.equal((await call()).decks.length,1);const read=await call(`/${saved.id}`);assert.deepEqual(read.document,d);assert.equal(read.peers.length,1);d.title='Updated';assert.equal((await call(`/${saved.id}`,'PUT',{version:1,document:d})).version,2);assert.equal((await call(`/${saved.id}?version=2`)).document,undefined);assert.equal((await call(`/${saved.id}`)).document.title,'Updated');});
test('stale concurrent writers cannot overwrite the winning revision',async()=>{const{call}=harness(),d=documentFixture(),saved=await call('','POST',{document:d});const a=structuredClone(d),b=structuredClone(d);a.title='Alice';b.title='Bob';const results=await Promise.all([call(`/${saved.id}`,'PUT',{version:1,document:a}),call(`/${saved.id}`,'PUT',{version:1,document:b})]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);assert.ok(['Alice','Bob'].includes((await call(`/${saved.id}`)).document.title));assert.equal((await call(`/${saved.id}`)).version,2);});
test('owner grants editor/viewer access; revocation affects every endpoint',async()=>{const{call}=harness(),d=documentFixture(),saved=await call('','POST',{document:d}),path=`/${saved.id}`;assert.equal((await call(path,'GET',null,'other')).status,403);assert.equal((await call('','GET',null,'other')).decks.length,0);await call(`${path}/members`,'PUT',{userId:'other',role:'editor'});assert.equal((await call('','GET',null,'other')).decks.length,1);assert.equal((await call(path,'PUT',{version:1,document:d},'other')).status,200);assert.equal((await call(`${path}/members`,'GET',null,'other')).status,403);await call(`${path}/members`,'PUT',{userId:'other',role:'viewer'});assert.equal((await call(path,'PUT',{version:2,document:d},'other')).status,403);assert.equal((await call(path,'GET',null,'other')).status,200);await call(`${path}/members`,'DELETE',{userId:'other'});assert.equal((await call(path,'GET',null,'other')).status,403);assert.equal((await call(path)).peers.some(p=>p.user_id==='other'),false);});
test('invalid shared documents never replace saved content',async()=>{const{call,files}=harness(),d=documentFixture(),saved=await call('','POST',{document:d});const invalid={...d,pages:[]};assert.equal((await call(`/${saved.id}`,'PUT',{version:1,document:invalid})).status,400);assert.equal(files.size,1);assert.equal((await call(`/${saved.id}`)).version,1);});
test('SQL parameters treat hostile collaborator identifiers as data',async()=>{const{call}=harness(),saved=await call('','POST',{document:documentFixture()});assert.equal((await call(`/${saved.id}/members`,'PUT',{userId:"x'); DROP TABLE decks;--",role:'viewer'})).status,200);assert.equal((await call()).decks.length,1);});
