import {test} from 'node:test';
import assert from 'node:assert/strict';
import {documentFixture,textElement} from './fixtures/document.mjs';
import {parsePaperDOMDocument,applyDocumentTransaction} from '../app/document-model.ts';
import {parseTable,parseChart,makeDataElement,copyElements,endpointPoint,resizePage,findText,resizeWithAspect,translateElement} from '../app/presentation-tools.ts';
import {effectiveLibrary} from '../app/starter-library.ts';
import {makeInstance} from '../app/component-library.ts';
test('table parser pads cells, preserves empty cells and rejects oversize data',()=>{assert.deepEqual(parseTable('A\tB\n1'),[['A','B'],['1','']]);assert.deepEqual(parseTable(''),[['']]);assert.throws(()=>parseTable(Array(51).fill('x').join('\n')));assert.throws(()=>parseTable(Array(21).fill('x').join('\t')));});
test('chart parser supports zero, negative and decimal values; rejects nonfinite, missing and extra columns',()=>{assert.deepEqual(parseChart('A\t0\nB\t-3.5'),{labels:['A','B'],values:[0,-3.5]});for(const text of['','A\t','\t1','A\tNaN','A\tInfinity','A\t1\t2'])assert.throws(()=>parseChart(text));});
for(const type of ['table','chart'])test(`${type} validates and survives JSON serialization`,()=>{const d=documentFixture();d.pages[0].elements.push(makeDataElement(type,type));const result=parsePaperDOMDocument(JSON.parse(JSON.stringify(d)));assert.equal(result.ok,true);});
for(const [name,mutate] of [
 ['ragged table',e=>e.table.rows.push(['bad'])],['non-string cell',e=>e.table.rows[0][0]=3],['empty table',e=>e.table.rows=[]],['chart mismatched series',e=>e.chart.values.pop()],['chart infinity',e=>e.chart.values[0]=Infinity],['chart kind',e=>e.chart.kind='pie']
])test(`schema rejects ${name} without mutating document`,()=>{const d=documentFixture();const e=makeDataElement(name.startsWith('chart')?'chart':'table','bad');mutate(e);const before=structuredClone(d);const r=applyDocumentTransaction(d,{operations:[{op:'createElement',element:e}]},d.pages[0].id);assert.equal(r.ok,false);assert.deepEqual(d,before);});
test('page presentation properties validate together and reject all-hidden decks',()=>{const d=documentFixture();for(const patch of[{advanceSeconds:-1},{advanceSeconds:3601},{transition:'morph'},{hidden:true}]){const r=applyDocumentTransaction(d,{operations:[{op:'patchPage',patch}]},d.pages[0].id);assert.equal(r.ok,false);}const r=applyDocumentTransaction(d,{operations:[{op:'patchPage',patch:{notes:'Speaker notes',transition:'fade',advanceSeconds:2}}]},d.pages[0].id);assert.equal(r.ok,true);});
test('clipboard deep clones groups, remaps included targets and detaches omitted targets',()=>{const p=documentFixture().pages[0];p.elements[0].groupId='g';p.elements.push({...textElement('line'),type:'connector',groupId:'g',from:{elementId:'text_1',anchor:'right'},to:{x:700,y:600}});const copies=copyElements(p,['text_1','line'],'copy');assert.equal(copies[1].from.elementId,copies[0].id);assert.equal(copies[0].groupId,copies[1].groupId);assert.notEqual(copies[0].groupId,'g');assert.deepEqual(copies[1].to,{x:720,y:620});copies[0].content.text='new';assert.equal(p.elements[0].content.text,'Hello');assert.deepEqual(copyElements(p,['line'],'alone')[0].from,{x:280,y:90});});
test('rotated connector anchors and translation stay connected',()=>{const e=textElement('r');e.frame={x:100,y:100,w:200,h:100,rotation:90};const p=endpointPoint({elementId:'r',anchor:'right'},[e]);assert.equal(Math.round(p.x),200);assert.equal(Math.round(p.y),250);const line={...textElement('l'),type:'connector',from:{elementId:'r',anchor:'right'},to:{x:10,y:20}};const moved=translateElement(line,30,-10);assert.deepEqual(moved.from,line.from);assert.deepEqual(moved.to,{x:40,y:10});assert.deepEqual(line.to,{x:10,y:20});});
test('page resize scales geometry and free endpoints independently',()=>{const p=documentFixture().pages[0];p.elements.push({...textElement('l'),type:'line',from:{x:100,y:100},to:{elementId:'text_1',anchor:'top'}});const r=resizePage(p,640,1440);assert.deepEqual(r.size,{width:640,height:1440});assert.equal(r.elements[0].frame.x,10);assert.equal(r.elements[0].frame.h,160);assert.deepEqual(r.elements[1].from,{x:50,y:200});assert.deepEqual(r.elements[1].to,p.elements[1].to);assert.equal(p.size.width,1280);});
test('aspect resizing preserves ratio and page bounds',()=>{const p=documentFixture().pages[0],f={x:10,y:10,w:200,h:100,rotation:0};const r=resizeWithAspect(f,{...f,w:2000,h:300},'se',p);assert.equal(r.w/r.h,2);assert.ok(r.x+r.w<=1280);assert.ok(r.y+r.h<=720);});
test('find covers text, tables and component default properties without case sensitivity',()=>{const d=documentFixture();const library=effectiveLibrary(d);d.library=library;d.pages[0].elements.push(makeDataElement('table','t'));const definition=library.components.find(c=>Object.keys(c.properties).length);const instance=makeInstance(definition,'instance');d.pages[0].elements.push(instance);assert.equal(findText(d,'HELLO')[0].elementId,'text_1');assert.ok(findText(d,'Revenue').some(e=>e.elementId==='t'));const value=Object.values(definition.properties)[0].default;assert.ok(findText(d,value).some(e=>e.elementId==='instance'));assert.deepEqual(findText(d,''),[]);});
