import {test} from 'node:test';
import assert from 'node:assert/strict';
import JSZip from 'jszip';
import {documentFixture,textElement} from './fixtures/document.mjs';
import {makeDataElement} from '../app/presentation-tools.ts';
import {createPowerPoint,standaloneHTML,exportElements} from '../app/presentation-export.ts';
import {createExampleDeck,exampleDecks} from '../app/starter-library.ts';
const unzip=async d=>JSZip.loadAsync(await createPowerPoint(d).write({outputType:'nodebuffer',compression:true}));
test('PPTX contains editable text, table, chart, notes, hidden slide and embedded image',async()=>{
 const d=documentFixture(),p=d.pages[0];p.notes='Explain the numbers';p.elements.push(makeDataElement('table','table'),makeDataElement('chart','chart'),{...textElement('image'),type:'image',content:{alt:'Pixel',src:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9l8AAAAASUVORK5CYII='}});d.pages.push({...structuredClone(p),id:'hidden',hidden:true,elements:[]});
 const zip=await unzip(d);const xml=await zip.file('ppt/slides/slide1.xml').async('string');assert.match(xml,/<a:t>Hello<\/a:t>/);assert.match(xml,/<a:tbl>/);assert.match(xml,/<c:chart/);assert.match(xml,/<p:pic>/);assert.match(await zip.file('ppt/notesSlides/notesSlide1.xml').async('string'),/Explain the numbers/);assert.match(await zip.file('ppt/slides/slide2.xml').async('string'),/show="0"/);assert.ok(Object.keys(zip.files).some(n=>n.startsWith('ppt/media/')&&n.endsWith('.png')));assert.match(await zip.file('ppt/charts/chart1.xml').async('string'),/Quarterly progress/);
});
test('PPTX preserves text emphasis and rotation',async()=>{const d=documentFixture(),e=d.pages[0].elements[0];e.style={...e.style,underline:true,strike:true,fontStyle:'italic',fontWeight:700};e.frame.rotation=45;const xml=await(await unzip(d)).file('ppt/slides/slide1.xml').async('string');assert.match(xml,/u="sng"/);assert.match(xml,/rot="2700000"/);assert.match(xml,/b="1"/);assert.match(xml,/i="1"/);});
test('external images fail explicitly instead of silently disappearing from PowerPoint',()=>{const d=documentFixture();d.pages[0].elements.push({...textElement('image'),type:'image',content:{src:'https://example.com/image.png',alt:'External'}});assert.throws(()=>createPowerPoint(d),/Embed/);});
test('HTML escapes hostile strings and keeps user content out of script',()=>{const d=documentFixture();d.title='</title><script>alert(1)</script>';d.pages[0].elements[0].content.text='<img src=x onerror=alert(1)>';d.pages[0].notes='private speaker note';const html=standaloneHTML(d);assert.ok(html.includes('&lt;img src=x onerror=alert(1)&gt;'));assert.equal((html.match(/<script>/g)||[]).length,1);assert.ok(!html.includes('private speaker note'));assert.ok(html.includes('Previous'));});
test('HTML excludes hidden slides and objects and exports data objects',()=>{const d=documentFixture(),p=d.pages[0];p.elements[0].hidden=true;p.elements.push(makeDataElement('table','table'),makeDataElement('chart','chart'));d.pages.push({...structuredClone(p),id:'hidden',name:'TOP SECRET',hidden:true,elements:[]});const html=standaloneHTML(d);assert.ok(!html.includes('TOP SECRET'));assert.ok(!html.includes('Hello'));assert.ok(html.includes('<table'));assert.ok(html.includes('Quarterly progress'));assert.ok(html.includes('<svg'));});
test('all example decks export component content as editable primitives',async()=>{for(const {id} of exampleDecks){const d=createExampleDeck(id);assert.ok(exportElements(d.pages[0],d).every(e=>e.type!=='component'));const zip=await unzip(d);assert.ok(zip.file('ppt/slides/slide1.xml'));}});
test('vendored export runtime retains exact provenance and excludes vulnerable image parsers',async()=>{const {readFile}=await import('node:fs/promises');const {createHash}=await import('node:crypto');const root=new URL('../vendor/pptxgenjs/',import.meta.url);const hashes=JSON.parse(await readFile(new URL('SHA256.json',root),'utf8'));for(const [file,hash]of Object.entries(hashes))assert.equal(createHash('sha256').update(await readFile(new URL(file,root))).digest('hex'),hash);const lock=JSON.parse(await readFile(new URL('../package-lock.json',import.meta.url),'utf8'));assert.ok(!Object.keys(lock.packages).some(p=>p.endsWith('/image-size')));assert.match(await readFile(new URL('LICENSE',root),'utf8'),/Brent Ely/);});
test('legacy style defaults are normalized before export',async()=>{const d=documentFixture();delete d.pages[0].elements[0].style.fontFamily;delete d.pages[0].elements[0].style.padding;assert.ok(standaloneHTML(d).includes('Hello'));assert.ok((await unzip(d)).file('ppt/slides/slide1.xml'));});
