'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {mergeDocuments,sameDocument} from './collaboration-model.ts';
import {parsePaperDOMDocument,type PaperDOMDocument} from './document-model.ts';
type Snapshot={id:string;version:number;document:PaperDOMDocument;role:string};
type Peer={user_id:string;name:string};
type APIResponse=Snapshot&{error?:string;peers?:Peer[];userId:string;decks:{id:string;title:string}[];members:{user_id:string;role:string}[]};
async function api(path:string,method='GET',data?:unknown){const response=await fetch(`/api/decks${path}`,{method,headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const value=await response.json() as APIResponse;if(!response.ok)throw Object.assign(new Error(value.error??'Shared document request failed'),{status:response.status});return value;}
export function useCloud(getDocument:()=>PaperDOMDocument,accept:(d:PaperDOMDocument)=>void,isBusy:()=>boolean){
 const [session,setSession]=useState<Snapshot|null>(null),[status,setStatus]=useState('Local document'),[peers,setPeers]=useState<Peer[]>([]),[conflicts,setConflicts]=useState<string[]>([]);
 const base=useRef<Snapshot|null>(null),latest=useRef({getDocument,accept,isBusy}),blocked=useRef(false),generation=useRef(0);
 useEffect(()=>{latest.current={getDocument,accept,isBusy};});
 const connect=useCallback((snapshot:Snapshot)=>{generation.current++;base.current=snapshot;blocked.current=false;setConflicts([]);setSession(snapshot);setStatus('Shared document connected');const url=new URL(location.href);url.searchParams.set('deck',snapshot.id);history.replaceState(null,'',url);},[]);
 const open=useCallback(async(id:string)=>{const snapshot=await api(`/${encodeURIComponent(id)}`);const parsed=parsePaperDOMDocument(snapshot.document);if(!parsed.ok)throw new Error(parsed.error);if(latest.current.isBusy())throw new Error('Finish the current edit before opening a document.');connect({...snapshot,document:parsed.document});latest.current.accept(parsed.document);},[connect]);
 const save=async()=>{const snapshot=await api('','POST',{document:latest.current.getDocument()});connect(snapshot);};
 const disconnect=()=>{generation.current++;base.current=null;setSession(null);blocked.current=false;setConflicts([]);setStatus('Local document');const url=new URL(location.href);url.searchParams.delete('deck');history.replaceState(null,'',url);};
 useEffect(()=>{const id=new URL(location.href).searchParams.get('deck');const timer=setTimeout(()=>{if(id)void open(id).catch(e=>setStatus(e.message));},0);return()=>clearTimeout(timer);},[open]);
 useEffect(()=>{if(!session)return;let active=true,running=false;
  const tick=async()=>{if(running||blocked.current||latest.current.isBusy()||!base.current)return;running=true;const ticket=generation.current;
   try{const previous=base.current;const remote=await api(`/${previous.id}?version=${previous.version}`);if(!active||ticket!==generation.current||latest.current.isBusy())return;setPeers(remote.peers??[]);
    if(remote.document){const parsed=parsePaperDOMDocument(remote.document);if(!parsed.ok)throw new Error(parsed.error);const local=latest.current.getDocument();if(sameDocument(local,previous.document)){latest.current.accept(parsed.document);}else{const merged=mergeDocuments(previous.document,local,parsed.document);if(merged.conflicts.length){blocked.current=true;setConflicts(merged.conflicts);setStatus('Conflicting edits need review. Your local changes are preserved.');return;}latest.current.accept(merged.document);}base.current={...remote,document:parsed.document};}
    const current=base.current!,local=structuredClone(latest.current.getDocument());if(!sameDocument(local,current.document)){
     if(remote.role==='viewer'){setStatus('Viewer access: edits remain local. Save a copy to keep them.');return;}
     setStatus('Saving shared changes…');const saved=await api(`/${current.id}`,'PUT',{version:current.version,document:local});if(!active||ticket!==generation.current)return;base.current={...current,version:saved.version,document:local};
    }setStatus('Shared changes saved');
   }catch(error){if(active&&ticket===generation.current){if((error as {status?:number}).status===409)setStatus('Receiving a newer revision…');else setStatus(error instanceof Error?error.message:'Offline: changes remain local');}}finally{running=false;}
  };void tick();const timer=setInterval(()=>void tick(),2000);return()=>{active=false;clearInterval(timer);};
 },[session]);
 return{session,status,peers,conflicts,open,save,disconnect,reload:()=>session?open(session.id):Promise.resolve()};
}
export function CloudPanel({cloud,onClose}:{cloud:ReturnType<typeof useCloud>;onClose:()=>void}){
 const [decks,setDecks]=useState<{id:string;title:string}[]>([]),[userId,setUserId]=useState(''),[members,setMembers]=useState<{user_id:string;role:string}[]>([]),[collaborator,setCollaborator]=useState(''),[role,setRole]=useState('editor'),[error,setError]=useState('');
 const run=async(fn:()=>Promise<unknown>)=>{try{setError('');await fn();}catch(e){setError(e instanceof Error?e.message:'Request failed');}};
 const refresh=async()=>{const data=await api('');setDecks(data.decks);setUserId(data.userId);};
 useEffect(()=>{let active=true;void api('').then(data=>{if(active){setDecks(data.decks);setUserId(data.userId);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 useEffect(()=>{if(cloud.session?.role!=='owner')return;let active=true;void api(`/${cloud.session.id}/members`).then(data=>{if(active)setMembers(data.members);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[cloud.session]);
 return <div className="json-backdrop" role="dialog" aria-modal="true" aria-label="Shared documents" onKeyDown={e=>e.stopPropagation()}><section className="rich-text-panel"><header><h2>Shared documents</h2><button onClick={onClose}>Close</button></header><p role="status">{cloud.status}</p>{error&&<p role="alert">{error}</p>}<button onClick={()=>run(async()=>{await cloud.save();await refresh();})}>Save current deck as shared copy</button>{cloud.session&&<><button onClick={()=>run(()=>navigator.clipboard.writeText(location.href))}>Copy document link</button><button onClick={cloud.disconnect}>Work on a local copy</button><p>Connected: {cloud.peers.map(p=>p.name).join(', ')||'You'}</p></>}{cloud.conflicts.length>0&&<div role="alert"><p>These fields changed in both copies:</p><ul>{cloud.conflicts.map(c=><li key={c}>{c}</li>)}</ul><p>Save your current deck as a shared copy to preserve your edits, or load the latest shared version.</p><button onClick={()=>run(cloud.reload)}>Discard local edits and load shared version</button></div>}<h3>Your decks</h3>{decks.map(d=><button key={d.id} onClick={()=>run(async()=>{await cloud.open(d.id);})}>{d.title}</button>)}<label>Your collaborator ID<input aria-label="Your collaborator ID" readOnly value={userId}/></label><p>Collaborators need access to this Site first. Ask them to copy their collaborator ID from this panel, then grant document access below.</p>{cloud.session?.role==='owner'&&<><label>Collaborator ID<input aria-label="Collaborator ID" value={collaborator} onChange={e=>setCollaborator(e.target.value)}/></label><select aria-label="Collaborator role" value={role} onChange={e=>setRole(e.target.value)}><option value="editor">Editor</option><option value="viewer">Viewer</option></select><button disabled={!collaborator.trim()} onClick={()=>run(async()=>{await api(`/${cloud.session!.id}/members`,'PUT',{userId:collaborator.trim(),role});setCollaborator('');setMembers((await api(`/${cloud.session!.id}/members`)).members);})}>Grant access</button>{members.map(m=><p key={m.user_id}>{m.user_id} · {m.role} <button onClick={()=>run(async()=>{await api(`/${cloud.session!.id}/members`,'DELETE',{userId:m.user_id});setMembers(members.filter(n=>n.user_id!==m.user_id));})}>Revoke access</button></p>)}</>}</section></div>;
}
