'use client';
import {useState} from 'react';
import type {CanvasPage,PaperDOMDocument,AgentTransactionPayload} from './document-model.ts';
import {findText,makeDataElement,resizePage} from './presentation-tools.ts';
import {auditDocument} from './agent-api.ts';
import {effectiveLibrary} from './starter-library.ts';
type Operation=AgentTransactionPayload['operations'][number];
export function EditorTools({document,page,selection,onTransaction,onSelect,onAction,onClose}:{document:PaperDOMDocument;page:CanvasPage;selection:string[];onTransaction:(operations:Operation[])=>void;onSelect:(pageId:string,ids:string[])=>void;onAction:(action:string)=>void|Promise<void>;onClose:()=>void}) {
  const [tab,setTab]=useState('Slides'),[query,setQuery]=useState(''),[replacement,setReplacement]=useState(''),[status,setStatus]=useState('');
  const run=async(action:()=>void|Promise<void>)=>{try{setStatus('');await action();}catch(e){setStatus(e instanceof Error?e.message:'Unable to complete action');}};
  const patch=(patch:Partial<CanvasPage>)=>onTransaction([{op:'patchPage',pageId:page.id,patch}]);
  const arrange=(direction:'left'|'center'|'right'|'top'|'middle'|'bottom'|'horizontal'|'vertical')=>{
    const selected=page.elements.filter(e=>selection.includes(e.id)&&!e.locked&&!e.hidden);if(selected.length<2)return;
    const l=Math.min(...selected.map(e=>e.frame.x)),r=Math.max(...selected.map(e=>e.frame.x+e.frame.w)),t=Math.min(...selected.map(e=>e.frame.y)),b=Math.max(...selected.map(e=>e.frame.y+e.frame.h));
    const positions=new Map<string,number>();
    if(direction==='horizontal'||direction==='vertical'){if(selected.length<3)throw new Error('Select at least three objects to distribute.');const horizontal=direction==='horizontal',ordered=[...selected].sort((a,b)=>horizontal?a.frame.x-b.frame.x:a.frame.y-b.frame.y);const total=ordered.reduce((sum,e)=>sum+(horizontal?e.frame.w:e.frame.h),0),gap=((horizontal?r-l:b-t)-total)/(ordered.length-1);let cursor=horizontal?l:t;for(const e of ordered){positions.set(e.id,cursor);cursor+=(horizontal?e.frame.w:e.frame.h)+gap;}}
    onTransaction(selected.map(e=>({op:'patchElement',elementId:e.id,patch:{frame:{x:direction==='left'?l:direction==='center'?(l+r-e.frame.w)/2:direction==='right'?r-e.frame.w:direction==='horizontal'?positions.get(e.id):e.frame.x,y:direction==='top'?t:direction==='middle'?(t+b-e.frame.h)/2:direction==='bottom'?b-e.frame.h:direction==='vertical'?positions.get(e.id):e.frame.y}}})));
  };
  const replaceAll=()=>{if(!query)return;const operations:Operation[]=[];const replace=(value:string)=>value.split(query).join(replacement);
    for(const p of document.pages)for(const e of p.elements){if(e.locked)continue;const patch:Record<string,unknown>={};if(e.content?.text?.includes(query))patch.content={...e.content,text:replace(e.content.text)};
      if(e.component){const def=effectiveLibrary(document).components.find(c=>c.id===e.component!.definitionId);const props={...e.component.props};let changed=false;for(const [key,property]of Object.entries(def?.properties??{})){const text=props[key]??property.default;if(text.includes(query)){props[key]=replace(text);changed=true;}}if(changed)patch.component={...e.component,props};}
      if(e.table?.rows.some(row=>row.some(cell=>cell.includes(query))))patch.table={...e.table,rows:e.table.rows.map(row=>row.map(replace))};
      if(Object.keys(patch).length)operations.push({op:'patchElement',pageId:p.id,elementId:e.id,patch});}
    if(operations.length)onTransaction(operations);setStatus(`${operations.length} objects updated. Replacement is case-sensitive.`);
  };
  return <section className="editor-tools" aria-label="Presentation tools"><header><nav>{['Slides','Objects','Find','Check & export'].map(name=><button key={name} aria-pressed={tab===name} onClick={()=>setTab(name)}>{name}</button>)}</nav><button aria-label="Close tools" onClick={onClose}>✕</button></header>
    {status&&<p role="status">{status}</p>}
    {tab==='Slides'&&<div className="tools-grid"><label>Current slide<select aria-label="Current slide" value={page.id} onChange={e=>onSelect(e.target.value,[])}>{document.pages.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>Speaker notes<textarea aria-label="Speaker notes editor" value={page.notes??''} onChange={e=>run(()=>patch({notes:e.target.value}))}/></label><div className="tools-stack"><label>Slide size<select aria-label="Slide size" value={`${page.size.width}x${page.size.height}`} onChange={e=>run(()=>{const[w,h]=e.target.value.split('x').map(Number);const resized=resizePage(page,w,h);onTransaction([{op:'patchPage',pageId:page.id,patch:{size:resized.size}},...resized.elements.map(element=>({op:'patchElement' as const,pageId:page.id,elementId:element.id,patch:{frame:element.frame,from:element.from,to:element.to}}))]);})}><option value="1280x720">Widescreen 16:9</option><option value="960x720">Standard 4:3</option><option value="720x1280">Portrait 9:16</option><option value="720x720">Square 1:1</option>{!['1280x720','960x720','720x1280','720x720'].includes(`${page.size.width}x${page.size.height}`)&&<option value={`${page.size.width}x${page.size.height}`}>Custom</option>}</select></label><label>Transition<select aria-label="Slide transition" value={page.transition??'none'} onChange={e=>run(()=>patch({transition:e.target.value as CanvasPage['transition']}))}><option value="none">None</option><option value="fade">Fade</option><option value="slide">Slide</option></select></label><label>Advance after seconds (0 = manual)<input type="number" aria-label="Advance after seconds" min="0" max="3600" value={page.advanceSeconds??0} onChange={e=>run(()=>patch({advanceSeconds:Math.max(0,Math.min(3600,Number(e.target.value)))}))}/></label><label className="tools-check"><input type="checkbox" checked={page.hidden??false} onChange={e=>run(()=>{if(e.target.checked&&document.pages.filter(p=>!p.hidden).length<2)throw new Error('Keep at least one slide visible.');patch({hidden:e.target.checked});})}/>Skip this slide in presentation</label></div><div className="tools-stack"><button onClick={()=>run(()=>onAction('addPage'))}>Add slide</button><button onClick={()=>run(()=>onAction('duplicatePage'))}>Duplicate slide</button><button onClick={()=>run(()=>onAction('previousPage'))}>Move slide earlier</button><button onClick={()=>run(()=>onAction('nextPage'))}>Move slide later</button><p>Size changes scale object positions and frames. Review text wrapping after resizing.</p></div></div>}
    {tab==='Objects'&&<div className="tools-grid"><div className="tools-stack"><button onClick={()=>onAction('inspector')}>Edit object properties</button><div className="tools-buttons">{['Copy','Cut','Paste','Duplicate','Group','Ungroup'].map(name=><button key={name} onClick={()=>run(()=>onAction(name.toLowerCase()))}>{name}</button>)}</div><div className="tools-buttons">{(['left','center','right','top','middle','bottom','horizontal','vertical']as const).map(d=><button key={d} onClick={()=>run(()=>arrange(d))}>{d==='horizontal'||d==='vertical'?`Distribute ${d}`:`Align ${d}`}</button>)}</div><div className="tools-buttons">{(['table','chart']as const).map(type=><button key={type} onClick={()=>run(()=>{const item=makeDataElement(type,`${type}_${(crypto.randomUUID?.()??Array.from(crypto.getRandomValues(new Uint8Array(16)),v=>v.toString(16).padStart(2,'0')).join(''))}`);item.frame.w=Math.min(item.frame.w,page.size.width);item.frame.h=Math.min(item.frame.h,page.size.height);item.frame.x=Math.max(0,(page.size.width-item.frame.w)/2);item.frame.y=Math.max(0,(page.size.height-item.frame.h)/2);onTransaction([{op:'createElement',element:item}]);onSelect(page.id,[item.id]);})}>Insert {type}</button>)}</div></div><div className="tools-layers" aria-label="Object list">{[...page.elements].sort((a,b)=>b.z-a.z).map(e=><div key={e.id}><button aria-label={`Select ${e.name}`} onClick={()=>onSelect(page.id,[e.id])}>{e.name}{e.groupId?' · grouped':''}</button><button aria-label={`${e.hidden?'Show':'Hide'} ${e.name}`} onClick={()=>run(()=>onTransaction([{op:'patchElement',elementId:e.id,patch:{hidden:!e.hidden}}]))}>{e.hidden?'Show':'Hide'}</button><button aria-label={`${e.locked?'Unlock':'Lock'} ${e.name}`} onClick={()=>run(()=>onTransaction([{op:'patchElement',elementId:e.id,patch:{locked:!e.locked}}]))}>{e.locked?'Unlock':'Lock'}</button></div>)}</div></div>}
    {tab==='Find'&&<div className="tools-grid"><div className="tools-stack"><label>Find text<input aria-label="Find text" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Replace with<input aria-label="Replace with" value={replacement} onChange={e=>setReplacement(e.target.value)}/></label><button disabled={!query} onClick={()=>run(replaceAll)}>Replace all</button><p>Find ignores case. Replace matches exact case and skips locked objects.</p></div><div className="tools-results">{findText(document,query).map(match=><button key={match.elementId} onClick={()=>onSelect(match.pageId,[match.elementId])}>{match.name}<small>{document.pages.find(p=>p.id===match.pageId)?.name}</small></button>)}</div></div>}
    {tab==='Check & export'&&<div className="tools-grid"><div className="tools-stack"><button onClick={()=>run(()=>onAction('pptx'))}>Download PowerPoint (.pptx)</button><button onClick={()=>run(()=>onAction('print'))}>Print / Save PDF</button><button onClick={()=>run(()=>onAction('html'))}>Download standalone HTML</button><button onClick={()=>run(()=>onAction('editJson'))}>Import / edit document JSON</button><button onClick={()=>run(()=>onAction('json'))}>Download document JSON</button><p>PowerPoint export keeps supported objects editable. Review fonts and wrapping in the target application. HTML export is a read-only offline deck.</p></div><div className="tools-results"><h3>Document checks</h3>{auditDocument(document).length?auditDocument(document).map((w,i)=><button key={i} onClick={()=>onSelect(w.pageId,[w.elementId])}>{w.message}</button>):<p>No missing image descriptions or out-of-page objects found. This is not a complete accessibility assessment.</p>}</div></div>}
  </section>;
}
