'use client';
import { useState } from 'react';
import type { CanvasPage } from './document-model.ts';
import { replaceRunText } from './advanced-model.ts';
export function MasterEditor({ master, onSave, onClose }: {
    master: CanvasPage;
    onSave: (master: CanvasPage) => void;
    onClose: () => void;
}) { const [draft, setDraft] = useState(() => structuredClone(master)); return <div className="json-backdrop" role="dialog" aria-modal="true" aria-label="Master editor" onKeyDown={e => e.stopPropagation()}><section className="rich-text-panel"><header><h2>Edit master</h2><button onClick={onClose}>Cancel</button></header><label>Master name<input aria-label="Master name" value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })}/></label><label>Background<input aria-label="Master background" type="color" value={draft.background.color} onChange={e => setDraft({ ...draft, background: { color: e.target.value } })}/></label>{draft.elements.map((item, i) => <fieldset key={item.id}><legend>{item.name}</legend>{item.content?.text !== undefined && <textarea aria-label={`Master text ${i + 1}`} value={item.content.text} onChange={e => setDraft({ ...draft, elements: draft.elements.map(n => n.id !== item.id ? n : { ...n, content: { ...n.content, text: e.target.value }, runs: n.runs ? replaceRunText(n.runs, e.target.value) : undefined }) })}/>}<div className="tools-buttons">{(['x', 'y', 'w', 'h', 'rotation'] as const).map(key => <label key={key}>{key}<input aria-label={`Master ${i + 1} ${key}`} type="number" value={item.frame[key]} onChange={e => { const value = Number(e.target.value); if (!Number.isFinite(value) || (['w', 'h'].includes(key) && value <= 0))
    return; setDraft({ ...draft, elements: draft.elements.map(n => n.id === item.id ? { ...n, frame: { ...n.frame, [key]: value } } : n) }); }}/></label>)}</div><button onClick={() => setDraft({ ...draft, elements: draft.elements.filter(n => n.id !== item.id && !['from', 'to'].some(side => n[side as 'from']?.elementId === item.id)) })}>Remove object</button></fieldset>)}<button className="present-button" onClick={() => { onSave(draft); onClose(); }}>Save master</button></section></div>; }
