import { addPowerPointTiming } from './pptx-timing.ts';
import { originalPowerPointBytes } from './pptx-source.ts';
import {masterObjects} from './pptx-masters.ts';
import JSZip from 'jszip';
import {composePage,textRuns} from './advanced-model.ts';
import PptxGenJS from '../vendor/pptxgenjs/pptxgen.es.js';
import type {CanvasElement,CanvasPage,PaperDOMDocument} from './document-model.ts';
import {parsePaperDOMDocument} from './document-model.ts';
import {resolveComponent,defaultTheme} from './component-library.ts';
import {effectiveLibrary} from './starter-library.ts';
import {endpointPoint} from './presentation-tools.ts';
const color=(value:string,fallback='172033')=>/^#[0-9a-f]{6}$/i.test(value)?value.slice(1):/^#[0-9a-f]{3}$/i.test(value)?value.slice(1).split('').map(c=>c+c).join(''):fallback;
const escape=(text:unknown)=>String(text??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const filename=(title:string)=>title.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'')||'PaperDOM';
export function exportElements(page:CanvasPage,document:PaperDOMDocument):CanvasElement[] {
  page=composePage(page,document);
  return [...page.elements].filter(e=>!e.hidden).sort((a,b)=>a.z-b.z).flatMap(e=>{
    if(e.type!=='component')return[structuredClone(e)];const children=resolveComponent(e,effectiveLibrary(document),document.theme??defaultTheme).filter(c=>!c.hidden).sort((a,b)=>a.z-b.z);const r=e.frame.rotation*Math.PI/180;
    return children.map(c=>{const n=structuredClone(c),dx=c.frame.x+c.frame.w/2-e.frame.w/2,dy=c.frame.y+c.frame.h/2-e.frame.h/2;n.id=`${e.id}_${c.id}`;n.frame={...c.frame,x:e.frame.x+e.frame.w/2+dx*Math.cos(r)-dy*Math.sin(r)-c.frame.w/2,y:e.frame.y+e.frame.h/2+dx*Math.sin(r)+dy*Math.cos(r)-c.frame.h/2,rotation:c.frame.rotation+e.frame.rotation};n.style.opacity*=e.style.opacity;
      for(const side of ['from','to']as const)if(c[side]){const p=endpointPoint(c[side],children),dx=p.x-e.frame.w/2,dy=p.y-e.frame.h/2;n[side]={x:e.frame.x+e.frame.w/2+dx*Math.cos(r)-dy*Math.sin(r),y:e.frame.y+e.frame.h/2+dx*Math.sin(r)+dy*Math.cos(r)};}return n;});
  });
}
export function createPowerPoint(document:PaperDOMDocument) {
  const parsed=parsePaperDOMDocument(document);if(!parsed.ok)throw new Error(parsed.error);document=parsed.document;
  const pptx=new PptxGenJS();const first=document.pages[0];pptx.defineLayout({name:'PAPERDOM',width:first.size.width/96,height:first.size.height/96});pptx.layout='PAPERDOM';pptx.title=document.title;pptx.subject='Created in PaperDOM';pptx.author='PaperDOM';
  const nativeMasters=new Set<string>();for(const master of document.masters??[]){if(master.size.width!==first.size.width||master.size.height!==first.size.height)continue;const objects=masterObjects(exportElements(master,document));if(objects){pptx.defineSlideMaster({title:master.id,objects,background:{color:color(master.background.color,'FFFFFF')}});nativeMasters.add(master.id);}}
  for(const source of document.pages){const composed=composePage(source,document);const native=source.masterId&&nativeMasters.has(source.masterId)&&source.size.width===first.size.width&&source.size.height===first.size.height;const page=native?{...source,masterId:undefined,background:composed.background}:composed;const slide=pptx.addSlide(native?source.masterId:undefined);slide.hidden=!!page.hidden;slide.background={color:color(page.background.color,'FFFFFF')};if(page.notes)slide.addNotes(page.notes);const k=Math.min(first.size.width/page.size.width,first.size.height/page.size.height)/96;const ox=(first.size.width-page.size.width*k*96)/192,oy=(first.size.height-page.size.height*k*96)/192;
    const elements=exportElements(page,document);
    for(const e of elements){const f=e.frame,s=e.style;const box={objectName:e.id,x:ox+f.x*k,y:oy+f.y*k,w:f.w*k,h:f.h*k,rotate:((f.rotation%360)+360)%360};const textStyle={...box,color:color(s.color),fontFace:s.fontFamily.split(',')[0].replace(/["']/g,''),fontSize:s.fontSize*.75*(k*96),bold:s.fontWeight>=650,italic:s.fontStyle==='italic',underline:s.underline?{style:'sng' as const}:undefined,strike:s.strike,align:s.textAlign,valign:s.verticalAlign==='top'?'top' as const:s.verticalAlign==='bottom'?'bottom' as const:'middle' as const,margin:s.padding*.75,breakLine:false,transparency:Math.round((1-s.opacity)*100)};
      if(e.type==='line'||e.type==='connector'){const a=endpointPoint(e.from,[...page.elements,...elements]),b=endpointPoint(e.to,[...page.elements,...elements]);slide.addShape(pptx.ShapeType.line,{objectName:e.id,x:ox+Math.min(a.x,b.x)*k,y:oy+Math.min(a.y,b.y)*k,w:Math.max(.001,Math.abs(b.x-a.x)*k),h:Math.max(.001,Math.abs(b.y-a.y)*k),flipH:b.x<a.x,flipV:b.y<a.y,line:{color:color(s.stroke),width:s.strokeWidth*.75,transparency:Math.round((1-s.opacity)*100),dashType:s.lineStyle==='dashed'?'dash':'solid',endArrowType:e.type==='connector'?'triangle':undefined}});continue;}
      if(e.type==='image'&&e.content?.src){if(!/^data:image\/(png|jpeg|gif|svg\+xml);/i.test(e.content.src))throw new Error(`Embed ${e.name} as PNG, JPEG, GIF, or SVG before PowerPoint export. External and WebP images are not exported.`);slide.addImage({...box,data:e.content.src,altText:e.content.alt??e.name,transparency:Math.round((1-s.opacity)*100)});continue;}
      if((e.type==='audio'||e.type==='video')&&e.media){if(!e.media.src.startsWith('data:'))throw new Error(`Embed ${e.name} before PowerPoint export.`);const mime=e.media.src.split(';')[0].split('/')[1];slide.addMedia({...box,type:e.type,data:e.media.src,extn:mime==='mpeg'?'mp3':mime,cover:e.media.poster?.startsWith('data:')?e.media.poster:undefined});continue;}
      if(e.type==='table'&&e.table){slide.addTable(e.table.rows.map((row,r)=>row.map(text=>({text,options:{bold:r===0&&e.table!.header,fill:{color:r===0&&e.table!.header?'EEEAFE':'FFFFFF'}}}))),{...box,fontFace:textStyle.fontFace,fontSize:textStyle.fontSize,color:textStyle.color,margin:6,border:{type:'solid',color:'CBD5E1',pt:1},autoPage:false,rowH:box.h/e.table.rows.length});continue;}
      if(e.type==='chart'&&e.chart){slide.addChart(e.chart.kind==='bar'?pptx.ChartType.bar:pptx.ChartType.line,[{name:e.chart.title,labels:e.chart.labels,values:e.chart.values}],{...box,barDir:'col',showLegend:false,showTitle:true,title:e.chart.title,showValue:true,chartColors:['6D5DFC']});continue;}
      if(e.type!=='text'||s.fill!=='transparent'||(s.strokeWidth>0&&s.stroke!=='transparent'))slide.addShape(e.type==='ellipse'?pptx.ShapeType.ellipse:s.radius>0?pptx.ShapeType.roundRect:pptx.ShapeType.rect,{...box,fill:{color:color(s.fill,'FFFFFF'),transparency:s.fill==='transparent'?100:Math.round((1-s.opacity)*100)},line:{color:color(s.stroke,'FFFFFF'),width:s.strokeWidth*.75,transparency:s.stroke==='transparent'?100:Math.round((1-s.opacity)*100)}});
      const text=e.type==='plugin'?[e.content?.label,e.content?.value,e.content?.trend].filter(Boolean).join('\n'):e.content?.text??(e.type==='image'?e.content?.alt??'Image':'');if(text)slide.addText(e.runs?textRuns(e).map(r=>({text:r.text,options:{fontFace:r.style?.fontFamily,fontSize:r.style?.fontSize===undefined?undefined:r.style.fontSize*.75*(k*96),bold:r.style?.fontWeight===undefined?undefined:r.style.fontWeight>=650,italic:r.style?.fontStyle===undefined?undefined:r.style.fontStyle==='italic',underline:r.style?.underline?{style:'sng' as const}:undefined,strike:r.style?.strike,color:r.style?.color?color(r.style.color):undefined,hyperlink:r.link?{url:r.link}:undefined}})):text,textStyle);
    }
  }
  return pptx;
}
/** Store the editable source alongside standard slides for lossless PaperDOM re-import. */
export async function powerPointBytes(document:PaperDOMDocument, options: { regenerate?: boolean } = {}){const original = !options.regenerate ? await originalPowerPointBytes(document) : null; if(original) return original; const zip=await JSZip.loadAsync(await createPowerPoint(document).write({outputType:'uint8array',compression:true}) as Uint8Array);for(const [index,page]of document.pages.entries()){const path=`ppt/slides/slide${index+1}.xml`;let xml=await zip.file(path)!.async('string');const audioIds=new Set(exportElements(page,document).filter(e=>e.type==='audio').map(e=>escape(e.id)));xml=xml.replace(/<p:pic>[\s\S]*?<\/p:pic>/g,pic=>[...audioIds].some(id=>pic.includes(`name="${id}"`))?pic.replace('<a:videoFile','<a:audioFile'):pic);zip.file(path,addPowerPointTiming(xml,page,document.pages[0].size));}zip.file('paperdom/document.json',JSON.stringify({...document,powerPointSource:undefined}));const content=await zip.file('[Content_Types].xml')!.async('string');zip.file('[Content_Types].xml',content.replace('</Types>','<Override PartName="/paperdom/document.json" ContentType="application/json"/></Types>'));return zip.generateAsync({type:'uint8array',compression:'DEFLATE'});}
export async function downloadPowerPoint(document:PaperDOMDocument){const bytes=await powerPointBytes(document);const url=URL.createObjectURL(new Blob([bytes as Uint8Array<ArrayBuffer>],{type:'application/vnd.openxmlformats-officedocument.presentationml.presentation'}));const a=window.document.createElement('a');a.href=url;a.download=`${filename(document.title)}.pptx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export function standaloneHTML(document:PaperDOMDocument) {
  const parsed=parsePaperDOMDocument(document);if(!parsed.ok)throw new Error(parsed.error);document=parsed.document;
  const pages=document.pages.filter(p=>!p.hidden).map((source,index)=>{const page=composePage(source,document);
    const elements=exportElements(page,document);const content=elements.map(e=>{const f=e.frame,s=e.style;const style=`position:absolute;left:${f.x}px;top:${f.y}px;width:${f.w}px;height:${f.h}px;transform:rotate(${f.rotation}deg);opacity:${s.opacity};background:${s.fill==='transparent'?'transparent':'#'+color(s.fill,'FFFFFF')};border:${s.strokeWidth}px solid ${s.stroke==='transparent'?'transparent':'#'+color(s.stroke)};border-radius:${e.type==='ellipse'?'50%':s.radius+'px'};color:#${color(s.color)};font-size:${s.fontSize}px;font-weight:${s.fontWeight};font-style:${s.fontStyle};text-align:${s.textAlign};line-height:${s.lineHeight};letter-spacing:${s.letterSpacing}px;padding:${s.padding}px;white-space:pre-wrap;overflow:hidden;box-sizing:border-box;display:flex;align-items:${s.verticalAlign==='top'?'flex-start':s.verticalAlign==='bottom'?'flex-end':'center'};text-decoration:${s.underline?'underline ':''}${s.strike?'line-through':''};`;
      if(e.type==='line'||e.type==='connector'){const a=endpointPoint(e.from,[...page.elements,...elements]),b=endpointPoint(e.to,[...page.elements,...elements]);return `<svg aria-hidden="true" viewBox="0 0 ${page.size.width} ${page.size.height}" style="position:absolute;inset:0;width:100%;height:100%;pointer-events:none"><defs><marker id="arrow${index}_${escape(e.id)}" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#${color(s.stroke)}"/></marker></defs><line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="#${color(s.stroke)}" stroke-width="${s.strokeWidth}" stroke-dasharray="${s.lineStyle==='dashed'?'10 8':'none'}" ${e.type==='connector'?`marker-end="url(#arrow${index}_${escape(e.id)})"`:''}/></svg>`;}
      let inside=textRuns(e).map(r=>{const st=r.style??{},style=`font-size:${st.fontSize??s.fontSize}px;font-weight:${st.fontWeight??s.fontWeight};font-style:${st.fontStyle??s.fontStyle};color:#${color(st.color??s.color)};text-decoration:${st.underline?'underline ':''}${st.strike?'line-through':''}`;return `<span style="${style}">${r.link?`<a href="${escape(r.link)}" target="_blank" rel="noreferrer">${escape(r.text)}</a>`:escape(r.text)}</span>`;}).join('');
      if((e.type==='audio'||e.type==='video')&&e.media){const m=e.media;inside=`<${e.type} controls ${m.loop?'loop':''} ${m.muted?'muted':''} src="${escape(m.src)}" aria-label="${escape(e.content?.alt??e.name)}" style="width:100%;height:100%" ${m.poster?`poster="${escape(m.poster)}"`:''}>${m.captions?`<track kind="captions" src="${escape(m.captions)}" srclang="en" default>`:''}</${e.type}>`;}if(e.type==='plugin')inside=[e.content?.label,e.content?.value,e.content?.trend].map(escape).join('<br>');
      if(e.type==='image')inside=e.content?.src?.startsWith('data:image/')?`<img src="${escape(e.content.src)}" alt="${escape(e.content.alt)}" style="width:100%;height:100%;object-fit:contain">`:escape(e.content?.alt??'Image unavailable offline');
      if(e.table)inside=`<table style="width:100%;height:100%;border-collapse:collapse">${e.table.rows.map((row,r)=>`<tr>${row.map(cell=>`<${r===0&&e.table!.header?'th':'td'} style="border:1px solid #cbd5e1;padding:8px">${escape(cell)}</${r===0&&e.table!.header?'th':'td'}>`).join('')}</tr>`).join('')}</table>`;
      if(e.chart){const lo=Math.min(0,...e.chart.values),hi=Math.max(1,...e.chart.values),yy=(v:number)=>240-(v-lo)/(hi-lo)*190,step=520/e.chart.values.length;inside=`<svg viewBox="0 0 600 320" role="img" aria-label="${escape(e.chart.title)}" style="width:100%;height:100%"><text x="300" y="28" text-anchor="middle" font-size="20">${escape(e.chart.title)}</text>${e.chart.values.map((v,i)=>`<g>${e.chart!.kind==='bar'?`<rect x="${50+step*(i+.18)}" y="${Math.min(yy(0),yy(v))}" width="${step*.64}" height="${Math.max(1,Math.abs(yy(v)-yy(0)))}" fill="#6d5dfc"/>`:`<circle cx="${50+step*(i+.5)}" cy="${yy(v)}" r="5" fill="#6d5dfc"/>`}<text x="${50+step*(i+.5)}" y="285" text-anchor="middle" font-size="13">${escape(e.chart!.labels[i])}</text><text x="${50+step*(i+.5)}" y="${yy(v)-8}" text-anchor="middle" font-size="13">${v}</text></g>`).join('')}${e.chart.kind==='line'?`<polyline points="${e.chart.values.map((v,i)=>`${50+step*(i+.5)},${yy(v)}`).join(' ')}" fill="none" stroke="#6d5dfc" stroke-width="3"/>`:''}</svg>`;}
      return `<div style="${style}">${inside}</div>`;
    }).join('');return `<section data-width="${page.size.width}" data-height="${page.size.height}" aria-label="${escape(page.name)}" style="display:${index?'none':'block'};position:relative;width:${page.size.width}px;height:${page.size.height}px;background:#${color(page.background.color,'FFFFFF')};flex-shrink:0">${content}</section>`;
  }).join('');
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(document.title)}</title><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#10131b;font-family:Arial,sans-serif}main{height:calc(100% - 55px);display:flex;align-items:center;justify-content:center}nav{height:55px;display:flex;justify-content:center;align-items:center;gap:20px;color:white}button{padding:8px 18px;border-radius:6px;border:0;cursor:pointer}section{transform-origin:center}</style><main>${pages}</main><nav><button id="prev">Previous</button><span id="count"></span><button id="next">Next</button></nav><script>const slides=[...document.querySelectorAll('section')];let i=0;function show(){slides.forEach((s,j)=>{s.style.display=j===i?'block':'none';s.style.transform='scale('+Math.min((innerWidth-32)/Number(s.dataset.width),(innerHeight-80)/Number(s.dataset.height))+')'});document.querySelector('#count').textContent=(i+1)+' / '+slides.length;document.querySelector('#prev').disabled=i===0;document.querySelector('#next').disabled=i===slides.length-1}document.querySelector('#prev').onclick=()=>{i=Math.max(0,i-1);show()};document.querySelector('#next').onclick=()=>{i=Math.min(slides.length-1,i+1);show()};addEventListener('keydown',e=>{if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();i=Math.min(slides.length-1,i+1);show()}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();i=Math.max(0,i-1);show()}});addEventListener('resize',show);show();</script></html>`;
}
export function downloadHTML(document:PaperDOMDocument){const blob=new Blob([standaloneHTML(document)],{type:'text/html'}),url=URL.createObjectURL(blob),a=window.document.createElement('a');a.href=url;a.download=`${filename(document.title)}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
