import { baseStyle, defaultTheme, makeInstance, instantiateTemplate, type ComponentDefinition, type ComponentLibrary, type Theme } from './component-library.ts';
import type { CanvasElement, CanvasPage, ElementStyle, PaperDOMDocument } from './document-model.ts';

const node = (id: string, text: string, x: number, y: number, w: number, h: number, style: Partial<ElementStyle> = {}, type: 'text'|'shape'|'ellipse' = 'text'): CanvasElement => ({ id, type, name: id, frame: {x,y,w,h,rotation:0}, z: type === 'text' ? 2 : 1, content: {text}, style: {...baseStyle,...style} });
const surface = (w: number,h: number) => node('surface','',0,0,w,h,{fill:defaultTheme.surface,radius:22},'shape');
function definition(id: string,name: string,category: string,description: string,w: number,h: number,elements: CanvasElement[],fields: Record<string,string>,accentIds: string[]=[]): ComponentDefinition {
  const properties = Object.fromEntries(Object.entries(fields).map(([key,label]) => [key,{label,default:elements.find(e=>e.id===key)?.content?.text ?? ''}]));
  return { id:`paperdom.${id}`, version:'1.0.0',name,category,description,size:{width:w,height:h},properties,elements,
    bindings:Object.keys(fields).map(key=>({elementId:key,property:key,field:'text'})),
    tokens:elements.flatMap(e=>[
      {elementId:e.id,field:'fontFamily' as const,token:'fontFamily' as const},
      {elementId:e.id,field:'color' as const,token:(accentIds.includes(e.id)?'accent':e.style.color===defaultTheme.muted?'muted':'ink') as keyof Theme},
      ...(e.id==='surface'?[{elementId:e.id,field:'fill' as const,token:'surface' as const}]:[]),
      ...(e.id==='accent'?[{elementId:e.id,field:'fill' as const,token:'accent' as const}]:[]),
    ]) };
}
export const starterComponents: ComponentDefinition[] = [
  definition('heading','Section heading','Text','Eyebrow, title, and supporting line.',1080,150,[node('eyebrow','PRODUCT / 2026',0,0,1080,24,{fontSize:14,fontWeight:750,letterSpacing:2}),node('title','A clear idea. Beautifully explained.',0,38,1080, 60,{fontSize:46,fontWeight:750}),node('subtitle','Build your story with reusable pieces.',0,112,1080,32,{fontSize:21,color:defaultTheme.muted})],{eyebrow:'Eyebrow',title:'Title',subtitle:'Subtitle'},['eyebrow']),
  definition('metric','Metric card','Data','A headline number with context and a trend.',320,210,[surface(320,210),node('label','Monthly active users',24,24,272,28,{fontSize:17,color:defaultTheme.muted}),node('value','24.8k',24,68,272,68,{fontSize:52,fontWeight:750}),node('trend','↑ 18% this quarter',24,153,272,30,{fontSize:17,fontWeight:650})],{label:'Label',value:'Value',trend:'Trend'},['trend']),
  definition('quote','Quote','Story','An editorial quote with speaker and role.',740,260,[surface(740,260),node('quote','“The best tools make room for your ideas.”',32,30,676,136,{fontSize:32,fontWeight:650}),node('author','Alex Morgan',32,188,676,26,{fontSize:18,fontWeight:700}),node('role','Product designer',32,219,676,24,{fontSize:15,color:defaultTheme.muted})],{quote:'Quote',author:'Author',role:'Role'},['author']),
  definition('feature','Feature card','Story','A numbered feature with a short explanation.',330,260,[surface(330,260),node('number','01',24,22,282,40,{fontSize:24,fontWeight:750}),node('title','Composable by design',24, 80,282,70,{fontSize:27,fontWeight:700}),node('body','Small pieces. Shared styles. Your own story.',24,170,282, 60,{fontSize:18,color:defaultTheme.muted})],{number:'Number',title:'Title',body:'Description'},['number']),
  definition('callout','Callout','Text','Highlight the one thing people should remember.',1060,110,[surface(1060,110),node('accent','',0,0,6,110,{fill:defaultTheme.accent,radius:3},'shape'),node('title','The takeaway',28,20,1000,30,{fontSize:22,fontWeight:750}),node('body','A single source of truth for every presentation.',28, 60,1000,30,{fontSize:19,color:defaultTheme.muted})],{title:'Title',body:'Message'},['title']),
  definition('step','Process step','Diagram','One numbered step in a sequence.',310,160,[node('accent','',0,0,48,48,{fill:defaultTheme.accent,radius:16},'shape'),node('number','1',0,0,48,48,{fontSize:22,fontWeight:750,textAlign:'center',color:'#ffffff'}),node('title','Start with an idea',0,66,310,36,{fontSize:25,fontWeight:700}),node('body','Choose a template and make it yours.',0,112,310,48,{fontSize:18,color:defaultTheme.muted})],{number:'Number',title:'Title',body:'Description'}),
  definition('comparison','Comparison column','Data','A title and three parallel points.',490,310,[surface(490,310),node('title','With PaperDOM',28,24,434,42,{fontSize:29,fontWeight:750}),node('first','01   Reusable components',28,96,434,44,{fontSize:21}),node('second','02   Consistent themes',28,160,434,44,{fontSize:21}),node('third','03   Open, portable files',28,224,434,44,{fontSize:21})],{title:'Title',first:'First point',second:'Second point',third:'Third point'},['title']),
  definition('milestone','Roadmap milestone','Diagram','A date, deliverable, and status.',330,180,[node('date','Q1 / 2026',0,0,330,28,{fontSize:15,fontWeight:750,letterSpacing:1}),node('title','Lay the foundation',0,50,330,68,{fontSize:27,fontWeight:750}),node('status','Core editor · Complete',0,140,330,28,{fontSize:17,color:defaultTheme.muted})],{date:'Date',title:'Milestone',status:'Status'},['date']),
  definition('badge','Badge','Text','A compact label for status or categories.',210,48,[surface(210,48),node('label','OPEN SOURCE',12,4,186,40,{fontSize:14,fontWeight:750,letterSpacing:1,textAlign:'center'})],{label:'Label'},['label']),
  definition('footer','Slide footer','Text','A quiet signature and page marker.',1080,32,[node('label','PaperDOM / Built from small pieces',0,0,950,32,{fontSize:13,color:defaultTheme.muted}),node('page','01',980,0,100,32,{fontSize:13,textAlign:'right',color:defaultTheme.muted})],{label:'Label',page:'Page number'}),
];
// Preserve the white number on the filled process badge.
starterComponents.find(c=>c.id==='paperdom.step')!.tokens = starterComponents.find(c=>c.id==='paperdom.step')!.tokens.filter(t=>!(t.elementId==='number'&&t.field==='color'));
const instance = (kind: string,id: string,x: number,y: number,props:Record<string,string>={},w?:number,h?:number) => makeInstance(starterComponents.find(c=>c.id===`paperdom.${kind}`)!,id,{x,y,...(w?{w}:{}),...(h?{h}:{})},props);
const page = (id:string,name:string,elements:CanvasElement[],notes:string):CanvasPage => ({id,name,notes,size:{width:1280,height:720},background:{color:'#ffffff'},elements});
const head = (title:string,subtitle:string,eyebrow='PAPERDOM / COMPOSE') => instance('heading','heading',100, 60,{title,subtitle,eyebrow});
const foot = (n:string) => instance('footer','footer',100,658,{page:n});
export const starterLibrary: ComponentLibrary = {format:'paperdom-library',version:'1.0',name:'PaperDOM Essentials',components:starterComponents,templates:[
  {id:'paperdom.cover',name:'Title & introduction',description:'A confident opening with a clear promise.',page:page('cover','Introduction',[instance('badge','badge',100,110),instance('heading','heading',100,245,{eyebrow:'YOUR NEXT BIG IDEA',title:'Create once. Compose endlessly.',subtitle:'An open canvas for people and their agents.'}),foot('01')],'Introduce the idea and explain what your audience will learn.')},
  {id:'paperdom.metrics',name:'Key metrics',description:'Three numbers, one clear takeaway.',page:page('metrics','Key metrics',[head('Progress, in perspective.','A snapshot of what matters this quarter.'),instance('metric','metric1',100,274),instance('metric','metric2',480,274,{label:'Customer satisfaction',value:'96%',trend:'↑ 4 points'}),instance('metric','metric3',860,274,{label:'Time to first draft',value:'5 min',trend:'↓ 60% faster'}),instance('callout','takeaway',100,530,{title:'Momentum is building',body:'Every improvement compounds when the whole team can reuse it.'},1080, 90),foot('02')],'These are illustrative numbers. Replace them with verified measurements.')},
  {id:'paperdom.features',name:'Three features',description:'Explain three parts of your offering.',page:page('features','What makes it work',[head('Built to work together.','Everything you need to turn a thought into a story.'),instance('feature','feature1',100,285),instance('feature','feature2',475,285,{number:'02',title:'Shared visual language',body:'Change a theme once. Keep every piece in sync.'}),instance('feature','feature3',850,285,{number:'03',title:'Open to everyone',body:'Portable JSON. MIT licensed. Yours to extend.'}),foot('03')],'Give one concrete example for each feature.')},
  {id:'paperdom.comparison',name:'Side-by-side comparison',description:'Compare two approaches using matching criteria.',page:page('comparison','Compare approaches',[head('Make the difference visible.','Use the same criteria to help your audience decide.'),instance('comparison','before',100,275,{title:'One-off slides',first:'01   Copy and paste',second:'02   Manual restyling',third:'03   Changes drift apart'}),instance('comparison','after',690,275),foot('04')],'Explain the tradeoffs fairly and identify when each approach is useful.')},
  {id:'paperdom.process',name:'Three-step process',description:'Walk through an ordered workflow.',page:page('process','How it works',[head('From idea to shared story.','A small, repeatable workflow.'),instance('step','step1',100,300),instance('step','step2',485,300,{number:'2',title:'Compose your story',body:'Insert pieces and edit their properties.'}),instance('step','step3',870,300,{number:'3',title:'Share and remix',body:'Export a document or a reusable library.'}),instance('callout','takeaway',100,525,{title:'Your work stays editable',body:'Linked instances preserve content when definitions change.'},1080,100),foot('05')],'Demonstrate each step using the editor.')},
  {id:'paperdom.roadmap',name:'Roadmap',description:'Three milestones and a next action.',page:page('roadmap','What comes next',[head('Build what comes next.','A roadmap shaped by the people who use it.'),instance('milestone','m1',100,300),instance('milestone','m2',475,300,{date:'NOW',title:'Reusable building blocks',status:'Components + templates · Ready'}),instance('milestone','m3',850,300,{date:'NEXT',title:'A community collection',status:'Contributions · Welcome'}),instance('callout','takeaway',100,535,{title:'Start with one useful piece',body:'Create a component, export the library, and share it on GitHub.'},1080, 90),foot('06')],'Invite feedback and choose one next contribution.')},
]};
export const exampleDecks = [
  {id:'product-story',name:'Product story',description:'Six slides introducing a composable product.',templates:['cover','features','metrics','comparison','process','roadmap']},
  {id:'team-update',name:'Team update',description:'A focused three-slide progress report.',templates:['metrics','process','roadmap']},
  {id:'component-playground',name:'Component playground',description:'All 10 components, ready to inspect and remix.',templates:[]},
];
export function createExampleDeck(id:string):PaperDOMDocument {
  const example=exampleDecks.find(e=>e.id===id);if(!example) throw new Error('Example not found');
  const pages = example.templates.map((key,index)=>instantiateTemplate(starterLibrary.templates.find(t=>t.id===`paperdom.${key}`)!,`example_${id}_${index}`));
  if(id==='component-playground') for(const [index,c] of starterComponents.entries()) pages.push(page(`play_${index}`,c.name,[instance('heading',`play_${index}_title`,100,60,{title:c.name,subtitle:c.description,eyebrow:'COMPONENT PLAYGROUND'}),makeInstance(c,`play_${index}_component`,{x:100,y:310})],'Select the component and edit its properties in the inspector.'));
  return {format:'paperdom',version:'0.1',id:`example_${id}`,title:example.name,revision:0,pages,library:structuredClone(starterLibrary),theme:{...defaultTheme},plugins:[],metadata:{createdAt:'2026-09-05T00:00:00.000Z',updatedAt:'2026-09-05T00:00:00.000Z'}};
}
export const effectiveLibrary = (document:PaperDOMDocument) => document.library ?? starterLibrary;
